swagger: "2.0"
info:
  version: "0.0.1"
  title: "Basic Caching Example Using the OpenWeatherMap API"
host: "localhost"
basePath: "/" 
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
x-a127-services:
  #Defines our cache
  cache:
      ## Uncomment one cache provider
      provider: volos-cache-apigee
      #provider: volos-cache-memory
      #provider: volos-cache-redis
      options:
        name: weather-cache
        ttl: 60000
        
paths:
  /weather:
    x-swagger-router-controller: cache-controller
    x-a127-apply:
      # Applies the cache to our endpoint
      cache:
        # Gets the cache name by calling 
        # cacheKey() in /helpers/volos.js
        key:
            helper: volos
            function: cacheKey
    get:
      description: "Returns current weather in the specified city to the caller"
      operationId: getWeatherByCity
      parameters:
        - name: city
          in: query
          description: "The city you want weather for in the form city,state,country"
          required: true
          type: "string"
      responses:
        "200":
          description: "Success"
          schema: 
            $ref: WeatherResponse
        default:
          description: "Error"
          schema:
            $ref: ErrorResponse
definitions:
  WeatherResponse:
    properties: 
      base: 
        type: "string"
      clouds: 
        type: "object"
        properties: 
          all: 
            type: "number"
      cod: 
        type: "number"
      coord: 
        type: "object"
        properties: 
          lat: 
            type: "number"
          lon: 
            type: "number"
      dt: 
        type: "number"
      id: 
        type: "number"
      main: 
        type: "object"
        properties: 
          humidity: 
            type: "number"
          pressure: 
            type: "number"
          temp_max: 
            type: "number"
          temp_min: 
            type: "number"
          temp: 
            type: "number"
      name: 
        type: "string"
      sys: 
        type: "object"
        properties: 
          country: 
            type: "string"
          id: 
            type: "number"
          message: 
            type: "number"
          sunrise: 
            type: "number"
          sunset: 
            type: "number"
          type: 
            type: "number"
      weather: 
        type: "array"
        items: 
          type: "object"
          properties: 
            description: 
              type: "string"
            icon: 
              type: "string"
            id: 
              type: "number"
            main: 
              type: "string"
      wind: 
        type: "object"
        properties: 
          deg: 
            type: "number"
          speed: 
            type: "number"
  ErrorResponse:
    required:
      - "message"
    properties:
      message:
        type: "string"
