swagger: "2.0"
info:
  version: "0.0.1"
  title: "Quota Example Using the Basic OpenWeatherMap API"
host: "localhost"
basePath: "/" 
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
x-a127-services:
  ## Add the quota module
  quota:
    ## Uncomment one provider
    provider: "volos-quota-memory"
    #provider: "volos-quota-redis"
    #provider: "volos-quota-apigee"
    options:
      timeUnit: "minute"
      interval: 1 
      allow: 3 
paths:
  /weather:
    x-swagger-router-controller: weather
    x-a127-apply:
        quota:
          key:
            helper: volos
            function: clientIp 
    get:
      description: "Returns current weather in the specified city to the caller"
      operationId: getWeatherByCity
      parameters:
        - name: city
          in: query
          description: "The city you want weather for in the form city,state,country"
          required: true
          type: "string"
      responses:
        "200":
          description: "Success"
          schema: 
            $ref: "#/definitions/WeatherResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  WeatherResponse:
    properties: 
      base: 
        type: "string"
      clouds: 
        type: "object"
        properties: 
          all: 
            type: "number"
      cod: 
        type: "number"
      coord: 
        type: "object"
        properties: 
          lat: 
            type: "number"
          lon: 
            type: "number"
      dt: 
        type: "number"
      id: 
        type: "number"
      main: 
        type: "object"
        properties: 
          humidity: 
            type: "number"
          pressure: 
            type: "number"
          temp_max: 
            type: "number"
          temp_min: 
            type: "number"
          temp: 
            type: "number"
      name: 
        type: "string"
      sys: 
        type: "object"
        properties: 
          country: 
            type: "string"
          id: 
            type: "number"
          message: 
            type: "number"
          sunrise: 
            type: "number"
          sunset: 
            type: "number"
          type: 
            type: "number"
      wind: 
        type: "object"
        properties: 
          deg: 
            type: "number"
          speed: 
            type: "number"
  ErrorResponse:
    required:
      - "message"
    properties:
      message:
        type: "string"
